
server:
  port: 8081
spring:
  mail:
    username: 458051205@qq.com
    password: xntufimkwilibibf
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail.smtp.ssl.enable: true

